#!/bin/bash
#SBATCH -J redtest
#SBATCH -A CWALLACE-SL2-CPU
#SBATCH --nodes 1
#SBATCH --ntasks 10
#SBATCH --time 00:30:00
#SBATCH --mail-type FAIL
#SBATCH -p skylake-himem
#SBATCH --output=./err/%A_%a.err
shopt -s nullglob
. /etc/profile.d/modules.sh # Leave this line (enables the module command)
module purge                # Removes all modules still loaded
#module load default-impi    # REQUIRED - loads the basic environment
module load rhel7/default-peta4            # REQUIRED - loads the basic environment
module load r-4.0.2-gcc-5.4.0-xyx46xb
export I_MPI_PIN_ORDER=scatter # Adjacent domains have minimal sharing of caches/sockets
JOBID=$SLURM_JOB_ID
echo -e "JobID: $JOBID"
G=$(expr $SLURM_ARRAY_TASK_ID + 5757) ### this is the array variable, you can use it the way you want. In this example I use it to select the gene based on the line number in a file
fname=$(sed -n "$G"p traits_to_project_all_newUKBBFINGEN.txt)

Rscript --vanilla adapted-18-reduction-all.R $fname

